#!/bin/bash
#list="Io Izr ori Vo Voe Voe2 Vo_e Vo_e2 Vzr"
#Io ori [-3:5]; Izr Voe2 Vo_e  [-6:2]; Vo [-5.5:2.5]; Vzr [-2.5:5.5]
list="ori"
for i in $list;
do
gnuplot << EOF
set terminal postscript eps enhanced color size 8, 6 linewidth 1 font "Arial,30" 
set output "dos_$list.eps"
set key at graph 0.7,0.95
set key spacing 1.5
set xlabel "Energy (eV)"; set xrange [-3:5]; set xtics -6,1,16 scale 0.8
#arbitary unit
set ylabel "Density of states (arb.unit)"; set yrange [0:250]; unset ytics
#set ylabel "Density of states (arb.unit)" offset 1.0
set lmargin at screen 0.10
set rmargin at screen 0.96
set tmargin at screen 0.96
set bmargin at screen 0.17
set arrow 1 from 0, 0 to 0, 250 linestyle 0 linecolor '#000000' linewidth 2 nohead
plot "/home/zero/Desktop/Defect_ZrO2/c-ZrO2/0813/$list/dos/DOS0" using 1:2 with lines linecolor '#000000' lt 1 lw 2 title "Total", "/home/zero/Desktop/Defect_ZrO2/c-ZrO2/0813/$list/dos/O_p" using 1:2 with lines linecolor '#FF0000' lt 1 lw 2 title "O-p", "/home/zero/Desktop/Defect_ZrO2/c-ZrO2/0813/$list/dos/Zr_d" using 1:2 with lines linecolor '#0000CD' lt 1 lw 2 title "Zr-d"
EOF
done
