#!/bin/bash
#********** title ******************************
set terminal postscript eps enhanced color size 7.5, 6 linewidth 1.5 font "Arial,35" 
set output "ZrO2_T.eps"
set lmargin at screen 0.10; set rmargin at screen 0.96;
set tmargin at screen 0.96; set bmargin at screen 0.17

#********** Key ********************************
set key at graph 0.8,0.95; set key spacing 1.8

#********** x&ylabel ***************************
set xtics nomirror; unset x2tics; unset y2tics
set xlabel "Time (ps)";
set xtics 0,10,110 scale -1.2 font "Arial,30"; set xrange [0:80]

set ylabel "Lattice constant (A^°)" offset 2.0;
set ytics scale -1.2 font "Arial,30"; set yrange [5.12:5.25]

#********** Plot *******************************
plot "log.ysz0_T0.01" using 2:($7/10) with lines linecolor '#000000' lt 1 lw 2 title "0.01K", \
     "log.ysz0_T1" using 2:($7/10) with lines linecolor '#FF0000' lt 1 lw 2 title "1K", \
	 "log.ysz0_T100" using 2:($7/10) with lines linecolor '#0000FF' lt 1 lw 2 title "100K",\
	 "log.ysz0_T300" using 2:($7/10) with lines linecolor '#EE0000' lt 1 lw 2 title "300K", \
	 "log.ysz0_T800" using 2:($7/10) with lines linecolor '#00DD00' lt 1 lw 2 title "800K", \
	 "log.ysz0_T1200" using 2:($7/10) with lines linecolor '#0000AA' lt 1 lw 2 title "1200K"
set output

#Others
#set arrow 1 from 0, 0 to 0, 250 linestyle 0 linecolor '#000000' linewidth 2 nohead
#arbitary unit
#"hei-peaks.dat" using 1:(-130) with points linecolor '#00FF00' pt '|' lw 2 title "Bragg position"
